name: Build and stage steeltoe.io

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true
  DOTNET_VERSION: '8.0.x'
  DOCFX_SOURCE_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    name: Build and publish app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Generate API Browser docs
      shell: pwsh
      run: build/build-metadata.ps1

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: Steeltoe.io
        path: docs/api
